"""
Orchestrator for the Ticket Clustering Pipeline.

Runs all 4 combinations: 2 fusion strategies x 2 clustering methods.
Results are saved to outputs/ for inspection.

Usage:
    python run_pipeline.py
    python run_pipeline.py --config config.yaml
"""
import argparse
import json
import os

import numpy as np
import yaml
from sklearn.metrics import silhouette_score

from pipeline.ingest import load_data
from pipeline.impute import impute
from pipeline.preprocessing import preprocess
from pipeline.embeddings import load_model, generate_embeddings, enrich_with_tag_embeddings
from pipeline.operational_features import encode_metadata
from pipeline.fusion import concatenate_fusion, weighted_fusion
from pipeline.clustering import cluster
from pipeline.evaluation import evaluate, business_interpret


def run(config_path: str = 'config.yaml') -> dict:
    """
    Execute the full clustering pipeline and return evaluation results.

    Stages:
    1. Ingest -> 2. Preprocess -> 3. Embed -> 4. Encode metadata
    5. Fuse (3 strategies) -> 6. Cluster (2 methods each) -> 7. Evaluate

    Returns:
        dict mapping run_name -> evaluation results for all 6 runs.
    """
    with open(config_path) as f:
        config = yaml.safe_load(f)

    os.makedirs('outputs', exist_ok=True)

    # --- Stage 1-4: Shared preprocessing ---
    print("[1/7] Loading data...")
    df = load_data(config['data']['path'], config)

    print("[1b] Imputing missing type labels...")
    if config.get('imputation', {}).get('enabled', False):
        df = impute(df, config)

    print("[2/7] Preprocessing text...")
    df = preprocess(df, config)
    texts = df['text'].tolist()

    print("[3/7] Generating sentence embeddings (may take a few minutes)...")
    model = load_model(config)
    semantic_vecs = generate_embeddings(texts, config, model=model)

    if config['embeddings'].get('tag_enrichment', {}).get('enabled', False):
        print("[3b] Enriching semantic vectors with tag_1 embeddings...")
        semantic_vecs = enrich_with_tag_embeddings(semantic_vecs, df, config, model=model)
        print(f"     Semantic vector dim: {semantic_vecs.shape[1]} (text + tag)")

    print("[4/7] Encoding operational metadata...")
    operational_vecs = encode_metadata(df, config)

    # --- Stage 5: Fuse ---
    print("[5/7] Building fused representations...")
    alpha = config['fusion']['alpha']
    fused = {
        'concatenation': concatenate_fusion(semantic_vecs, operational_vecs),
        'weighted': weighted_fusion(semantic_vecs, operational_vecs, alpha),
    }

    # --- Stage 6-7: Cluster and evaluate ---
    print("[6/7] Clustering and evaluating (6 combinations)...")
    all_results = {}

    for fusion_name, vectors in fused.items():
        for method in ['kmeans', 'hdbscan']:
            run_name = f"{fusion_name}_{method}"
            print(f"  -> {run_name}")
            labels = cluster(vectors, method, config)
            results = _evaluate_run(vectors, labels, texts, config)
            all_results[run_name] = results
            df[f'cluster_{run_name}'] = labels

    # --- Save outputs ---
    print("[7/7] Saving outputs...")
    df.to_csv('outputs/clustered_tickets.csv', index=False)
    _save_evaluation_summary(all_results)
    _write_cluster_descriptions(all_results)

    print("\nDone. Results saved to outputs/")
    _print_summary_table(all_results)

    return all_results


def _evaluate_run(
    vectors: np.ndarray,
    labels: np.ndarray,
    texts: list,
    config: dict,
) -> dict:
    """Run evaluate() and business_interpret(), add silhouette score."""
    results = evaluate(vectors, labels, texts, config)
    results['business'] = business_interpret(results['cluster_keywords'], config)

    # Silhouette needs at least 2 clusters and 2 non-noise points
    mask = labels >= 0
    if mask.sum() > 1 and len(set(labels[mask])) > 1:
        sample_size = min(5000, int(mask.sum()))
        idx = np.random.choice(np.where(mask)[0], sample_size, replace=False)
        results['silhouette'] = float(silhouette_score(vectors[idx], labels[idx]))

    return results


def _save_evaluation_summary(all_results: dict):
    summary = {}
    for run_name, res in all_results.items():
        summary[run_name] = {
            'silhouette': res.get('silhouette'),
            'n_clusters': len([k for k in res['cluster_sizes'] if k >= 0]),
            'noise_count': res['cluster_sizes'].get(-1, 0),
            'cluster_sizes': res['cluster_sizes'],
            'cluster_keywords': res['cluster_keywords'],
            'business': res.get('business', {}),
        }
    with open('outputs/evaluation_summary.json', 'w') as f:
        json.dump(summary, f, indent=2)


def _write_cluster_descriptions(all_results: dict):
    lines = ['# Cluster Descriptions\n',
             'Generated by run_pipeline.py -- manual inspection in cluster_interpretation.ipynb.\n']
    for run_name, res in all_results.items():
        lines.append(f'\n## {run_name}\n')
        biz = res.get('business', {})
        sizes = res.get('cluster_sizes', {})
        for cid, interp in sorted(biz.items()):
            size = sizes.get(cid, 0)
            lines += [
                f'### Cluster {cid}: {interp["category"]}',
                f'- **Size:** {size} tickets',
                f'- **Routing team:** {interp["team"]}',
                f'- **Automation opportunity:** {"Yes" if interp["automation"] else "No"}',
                f'- **Confidence:** {interp["confidence"]}',
                f'- **Top keywords:** {", ".join(interp["top_keywords"])}',
                '',
            ]
    with open('outputs/cluster_descriptions.md', 'w') as f:
        f.write('\n'.join(lines))


def _print_summary_table(all_results: dict):
    print(f"\n{'Run':<30} {'Silhouette':>12} {'Clusters':>10} {'Noise':>8}")
    print('-' * 65)
    for run_name, res in all_results.items():
        sil = res.get('silhouette')
        sil_str = f'{sil:.4f}' if sil is not None else 'N/A'
        n_clusters = len([k for k in res['cluster_sizes'] if k >= 0])
        noise = res['cluster_sizes'].get(-1, 0)
        print(f'{run_name:<30} {sil_str:>12} {n_clusters:>10} {noise:>8}')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Run the IT ticket clustering pipeline.')
    parser.add_argument('--config', default='config.yaml', help='Path to config YAML')
    args = parser.parse_args()
    run(args.config)
